[package]
name = "plastic_core"
version = "0.1.0"
authors = ["Amjad Alsharafi <amjadsharafi10@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories-next = "2.0.0"
regex = "1.3.9"
bitflags = "^1.2.1"

serde = { version = "1.0.115", features = ["derive"] }
bincode = "1.3.1"

# used by the apu only
rodio = { version = "^0.11.0", default-features = false, features = [] }
